### ISSUE TITLE
Destroy function

### ISSUE THREAD

**Issue by adamnurdin01** [MightyMedia/Simple-Social-Share#1]
Hi,. thanks for your great plugin

I have a question. how to destroy this plugin on some event,.? 
example for event click,.

Regards

**Comment by basvandenwijngaard** [comment]
Hi Adam,

At this point this point the plugin has no way to destroy it. In what kind of situation would you think this will be useful? 

Do you want to be able to completely destroy the instances of the plugin (ie. `$('.mySelector').simpleSocialShare('destroy');` ).

Or do you want some sort of callback functionality which enable you to specifically destroy the plugin instance for the clicked link?

**Comment by basvandenwijngaard** [comment]
Hi Adam,

As af version 0.2.0 -released last week- you can destroy the plugin as described in my previous comment.

https://github.com/MightyMedia/Simple-Social-Share/releases/tag/v0.2.0

**Comment by adamnurdin01** [comment]
Awseome..

Thanks so much,.
