### ISSUE TITLE
Callback functionality

### ISSUE THREAD

**Issue by basvandenwijngaard** [MightyMedia/Simple-Social-Share#2]
Option to define a callback function after the click event is fired.

It should be possible to define a callback in the initializationd, but also via data-attr for each link apart.

**Comment by HarroH** [comment]
working on it

**Comment by basvandenwijngaard** [comment]
@HarroH ,

I assigned the issue to you.

**Comment by basvandenwijngaard** [comment]
Added with pull request #8
