### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by wwwmaster1** [MightyMedia/Simple-Social-Share#4]
Could not find the url of a live demo of this function.

**Comment by basvandenwijngaard** [comment]
That is correct. At the moment there isn't an official demo available online. You can, however see the plugin live in action on a few websites. Some of them are:

- [tennis.nl](https://tennis.nl/tennisinnederland/overijssel-in-vogelvlucht/) (the social icons on the left below the title).
- [resistentiepreventie.nl](https://www.resistentiepreventie.nl/nieuws/richtlijn-lage-luchtweginfecties/) (social icons on the right).
